### PR TITLE
 workaround-a-bug-triggered-by-unicode-causing-xmldsig-verification-error

### PR DESCRIPTION
**Pull request by colourful-land**
running this command on the line that contains 'var mappingStr'

$ grep -R var.mappingStr ./examples/ENS/recordsBundle.en.js | native2ascii -encoding UTF-8

Note that native2ascii is a commandline utility provided by JDK-8

This one fixes https://github.com/AlphaWallet/alpha-wallet-android/issues/1362 but only the symptom.

### CODE REVIEW

**Comment by James-Sangalli** [comment]
Also, are you sure this will work without problems?

**Comment by colourful-land** [comment]
> @colourful-land you need to put this into the build script located in the package.json otherwise this will have to be done by hand each time.

I can't with the tailing todo list. In fact, I used this quick workaround instead of finding the real problem in xmldsig verifier because I didn't have the time to do that...

**Comment by James-Sangalli** [comment]
@colourful-land I have added it to the package.json but this package seems to not be standard. I get the following error:

`Unable to locate an executable at "/Library/Java/JavaVirtualMachines/adoptopenjdk-13.0.2.jdk/Contents/Home/bin/native2ascii" (-1)
`

**Comment by James-Sangalli** [comment]
Doesn't work for android webview so I am closing this

**Comment by colourful-land** [comment]
I am making it work.

**Pull request closed without merging**
