### PR TITLE
Set resolver with subdomain

### PR DESCRIPTION
**Pull request by James-Sangalli**
Merge after #47

This PR:

- Allows the resolver to be set like in here: https://etherscan.io/tx/0xec92a480ecef2ca9a82d7420bd0df6cf4d12fcc3e14ab721025660c96e37d1c0
- uses the up to date contract
- renames the ref to match the name in the contract

### CODE REVIEW

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 this transaction allows the resolver to be set with the subdomain but we cannot keep track of the subdomains for now...

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 this transaction allows the resolver to be set with the subdomain but we cannot keep track of the subdomains for now...

we will need to explain this  the ens article and suggest the user test the subdomain before using it . and if they need a list, go to app.ens.domain

**Comment by James-Sangalli** [comment]
> > @zhangzhongnan928 this transaction allows the resolver to be set with the subdomain but we cannot keep track of the subdomains for now...
> 
> we will need to explain this the ens article and suggest the user test the subdomain before using it . and if they need a list, go to app.ens.domain

I think we will need to share the subdomains with ens to make it work

**Comment by zhangzhongnan928** [comment]
There are 2 type of users: 1. normal wallet users, they are just using ens to "replace" their address, normally they just use a free subdomain provided by their wallet provider  2. people who reg ens domains, they are investors and geeks. investor cares about renew/expire and etc. geeks want to use ens for everything, I have highlighted a few in my ens issues.

*Victor Zhang*
CEO , AlphaWallet

( http://apple.co/2OQRS7c ) ( http://play.google.com/store/apps/details?id=io.stormbird.wallet&hl=en_SG ) ( http://github.com/alphawallet ) ( http://twitter.com/Victor928 ) ( http://www.linkedin.com/in/zhangzhongnan/ ) ( http://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w ) ( http://www.facebook.com/AlphaWallet ) ( http://medium.com/alphawallet )

( https://twitter.com/Victor928 ) RT @AlphaWallet: ( https://twitter.com/AlphaWallet: ) Frustrated by the lack of a simple UI to wrap/unwrap WETH? try this tool by @JamesSangalli ( https://twitter.com/JamesSangalli ) https://t.co/HwO7SsOnTl Read More ( https://twitter.com/Victor928/statuses/1246556249262395392 )

Create your own WiseStamp email signature ( https://www.wisestamp.com/signature-in-email/?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own&srcid=5006976067829760 )

**Pull request merged**
