### PR TITLE
Redesign karma car layout token

### PR DESCRIPTION
**Pull request by ChintanRathod**
- Fixes https://github.com/AlphaWallet/TokenScript/issues/317
- Modify CSS with comments to create the styling constraints of the Karma Car layout

### CODE REVIEW

**Comment by James-Sangalli** [comment]
photo_2020-03-27_16-07-59

This is the old layout.

**Comment by ChintanRathod** [comment]
@James-Sangalli 
As discussed with @JamesSmartCell , hardcoded value for Holden year and Colour parameter due to not availability of attributes in to token. 
Please review and let me know.

**Comment by James-Sangalli** [comment]
IMG_DB166D75604F-1

Could you fix the whitespace below please?

**Comment by ChintanRathod** [comment]
@James-Sangalli Made height auto instead of any fixed pixels. Tested and working for multiple resolution without any white space. Please review.

**Pull request merged**
