### PR TITLE
adds quantity to fifa tickets in group

### PR DESCRIPTION
**Pull request by James-Sangalli**
Closes https://github.com/AlphaWallet/TokenScript/issues/313

This was not part of Tomek's design but it shows it clearly 

photo_2020-02-10_11-09-11

### CODE REVIEW

**Comment by hboon** [comment]
@James-Sangalli The spacing between the perforation line and "4x RUS" is gone in the screenshot.

**Comment by James-Sangalli** [comment]
@hboon on my phone I never had such spacing, I could add a % margin however 

photo_2020-02-10_11-33-20

**Comment by hboon** [comment]
@James-Sangalli oh right. I was referring to #313. Up to you.

**Comment by hboon** [comment]
@James-Sangalli oh right. I was referring to https://github.com/AlphaWallet/TokenScript/issues/313#issuecomment-570533496. Up to you.

**Comment by James-Sangalli** [comment]
@hboon addressed. 

IMG_8A296C61C95E-1

**Comment by hboon** [comment]
@James-Sangalli 👍

**Pull request merged**
